/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/auth/login-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Login Request */
        post: operations["create_login_request_api_admin_auth_login_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login-requests/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll Login Request
         * @description Подтверждён ли вход в боте. Подтверждённый — сессия в cookie, один раз (1.5).
         */
        post: operations["poll_login_request_api_admin_auth_login_requests_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_admin_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brand
         * @description Без входа: экран входа оформлен брендом оператора (1.23).
         */
        get: operations["brand_api_admin_brand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brand Settings */
        get: operations["brand_settings_api_admin_settings_brand_get"];
        /**
         * Update Brand Settings
         * @description Изменения видны сразу, без перезапуска (1.23); каждое — в журнале (4.25).
         */
        put: operations["update_brand_settings_api_admin_settings_brand_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/brand/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Palette
         * @description Предпросмотр в обеих темах до сохранения (1.24).
         */
        post: operations["preview_palette_api_admin_settings_brand_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/brand/assets/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Asset
         * @description Логотип — телом запроса с типом файла: image/svg+xml или image/png (0051).
         */
        put: operations["upload_asset_api_admin_settings_brand_assets__kind__put"];
        post?: never;
        /** Remove Asset */
        delete: operations["remove_asset_api_admin_settings_brand_assets__kind__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Checklist
         * @description Чек-лист первичной настройки (1.7).
         */
        get: operations["checklist_api_admin_checklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shop/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Shop Endpoint
         * @description «Открыть магазин» — когда выполнены обязательные пункты (1.14).
         */
        post: operations["open_shop_endpoint_api_admin_shop_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shop/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Shop Endpoint
         * @description Временно закрыть магазин (1.22).
         */
        post: operations["close_shop_endpoint_api_admin_shop_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shop Settings */
        get: operations["shop_settings_api_admin_settings_shop_get"];
        /**
         * Update Shop Settings
         * @description Контакт поддержки (чек-лист), часовой пояс (1.18), тестировщики (1.21).
         */
        put: operations["update_shop_settings_api_admin_settings_shop_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Settings */
        get: operations["login_settings_api_admin_settings_login_get"];
        /** Update Login Settings */
        put: operations["update_login_settings_api_admin_settings_login_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Panel Settings */
        get: operations["panel_settings_api_admin_settings_panel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/panel/webhook-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Webhook Secret
         * @description Свой секрет — например, уже заданный в панели для прежнего бота (0052).
         */
        put: operations["update_webhook_secret_api_admin_settings_panel_webhook_secret_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/panel/webhook-secret/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Webhook Secret
         * @description Новый секрет, созданный магазином: его нужно указать в панели.
         */
        post: operations["generate_webhook_secret_api_admin_settings_panel_webhook_secret_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/subscriptions/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Expiring
         * @description Подписки, истекающие в ближайшие 3 дня (1.17).
         */
        get: operations["expiring_api_admin_subscriptions_expiring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tariffs */
        get: operations["tariffs_api_admin_tariffs_get"];
        put?: never;
        /**
         * Create
         * @description Новый тариф «срок + безлимит» в продаже (2.1–2.3).
         */
        post: operations["create_api_admin_tariffs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/panel/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Squads
         * @description Сквады из панели — для выбора в форме тарифа (2.2).
         */
        get: operations["squads_api_admin_panel_squads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tariffs/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Order
         * @description Порядок тарифов в продаже, который видит клиент (2.4).
         */
        put: operations["order_api_admin_tariffs_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tariffs/{tariff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update
         * @description Новые параметры применяются при следующей покупке или продлении (2.5, 2.6).
         */
        put: operations["update_api_admin_tariffs__tariff_id__put"];
        post?: never;
        /**
         * Delete
         * @description Удалить тариф без подписок и платежей; иначе — только архив (2.8).
         *
         *     `confirm_last` — владелец видел предупреждение «последний тариф в продаже» (2.9).
         */
        delete: operations["delete_api_admin_tariffs__tariff_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tariffs/{tariff_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive
         * @description В архив (2.7); последний тариф в продаже — с подтверждением (2.9).
         */
        post: operations["archive_api_admin_tariffs__tariff_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tariffs/{tariff_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Вернуть в продажу (2.7).
         */
        post: operations["restore_api_admin_tariffs__tariff_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About */
        get: operations["about_api_admin_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AboutOut */
        AboutOut: {
            /** Version */
            version: string;
            /** License */
            license: string;
            /** Repository Url */
            repository_url: string;
            /** Font */
            font: string;
            /** Font License */
            font_license: string;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "mark" | "logo";
        /** AssetOut */
        AssetOut: {
            /** Url */
            url: string;
        };
        /** BrandDetailsOut */
        BrandDetailsOut: {
            /** Name */
            name: boolean;
            /** Mark */
            mark: boolean;
        };
        /**
         * BrandOut
         * @description Бренд для рамы: экран входа и все экраны админки (1.23).
         */
        BrandOut: {
            /** Name */
            name: string;
            /** Name Is Default */
            name_is_default: boolean;
            /** Mark Url */
            mark_url: string | null;
            /** Logo Url */
            logo_url: string | null;
            tokens: components["schemas"]["TokensOut"];
        };
        /** BrandSettingsIn */
        BrandSettingsIn: {
            name: components["schemas"]["remnabay__web__admin___brand___Name"];
            primary_color: components["schemas"]["Color"];
            secondary_color?: components["schemas"]["Color"] | null;
            welcome_text?: components["schemas"]["_Welcome"] | null;
        };
        /** BrandSettingsOut */
        BrandSettingsOut: {
            /** Name */
            name: string;
            /** Primary Color */
            primary_color: string;
            /** Secondary Color */
            secondary_color: string | null;
            /** Welcome Text */
            welcome_text: string;
            /** Welcome Text Is Default */
            welcome_text_is_default: boolean;
            mark: components["schemas"]["AssetOut"] | null;
            logo: components["schemas"]["AssetOut"] | null;
            palette: components["schemas"]["PaletteOut"];
        };
        /** ChecklistOut */
        ChecklistOut: {
            state: components["schemas"]["ShopState"];
            /** Can Open */
            can_open: boolean;
            /** Complete */
            complete: boolean;
            /** Items */
            items: components["schemas"]["ItemOut"][];
        };
        Color: string;
        /** ColorsIn */
        ColorsIn: {
            primary_color: components["schemas"]["Color"];
            secondary_color?: components["schemas"]["Color"] | null;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /**
             * Confirm Last
             * @default false
             */
            confirm_last: boolean;
        };
        /** ExpiringOut */
        ExpiringOut: {
            /** Subscription Id */
            subscription_id: number;
            /** Name */
            name: string;
            /** Is Trial */
            is_trial: boolean;
            /** Tariff Name */
            tariff_name: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Client Id */
            client_id: number;
            /** Telegram Id */
            telegram_id: number | null;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InUseOut */
        InUseOut: {
            /**
             * Reason
             * @default in_use
             * @constant
             */
            reason: "in_use";
            /** Message */
            message: string;
            /** Usage */
            usage: components["schemas"]["Usage"][];
        };
        /**
         * ItemKey
         * @enum {string}
         */
        ItemKey: "panel" | "webhook" | "device_limit" | "brand" | "tariffs" | "payment" | "support" | "trial" | "migration";
        /** ItemOut */
        ItemOut: {
            key: components["schemas"]["ItemKey"];
            status: components["schemas"]["ItemStatus"];
            /** Required */
            required: boolean;
            panel?: components["schemas"]["PanelDetailsOut"] | null;
            webhook?: components["schemas"]["WebhookDetailsOut"] | null;
            brand?: components["schemas"]["BrandDetailsOut"] | null;
            /** Trial Enabled */
            trial_enabled?: boolean | null;
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "done" | "todo" | "warning" | "optional";
        /** LastOnSaleOut */
        LastOnSaleOut: {
            /**
             * Reason
             * @default last_on_sale
             * @constant
             */
            reason: "last_on_sale";
            /** Message */
            message: string;
        };
        /** LoginPollOut */
        LoginPollOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "rejected" | "expired" | "signed_in";
        };
        /**
         * LoginRequestOut
         * @description Запрос входа: ссылка на бот и код, который бот покажет в подтверждении.
         */
        LoginRequestOut: {
            /** Bot Link */
            bot_link: string;
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LoginSettingsIn */
        LoginSettingsIn: {
            /** Login Ttl Minutes */
            login_ttl_minutes: number;
            /** Session Ttl Days */
            session_ttl_days: number;
        };
        /**
         * LoginSettingsOut
         * @description «Вход в админку»: срок подтверждения входа (1.5) и срок сессии.
         */
        LoginSettingsOut: {
            /** Login Ttl Minutes */
            login_ttl_minutes: number;
            /** Session Ttl Days */
            session_ttl_days: number;
        };
        /** MemberOut */
        MemberOut: {
            /** Id */
            id: number;
            /** Telegram Id */
            telegram_id: number;
            /** Name */
            name: string | null;
            role: components["schemas"]["TeamRole"];
        };
        /** NotReadyOut */
        NotReadyOut: {
            /** Missing */
            missing: components["schemas"]["ItemKey"][];
        };
        /** OrderIn */
        OrderIn: {
            /** Tariff Ids */
            tariff_ids: number[];
        };
        /**
         * OverviewOut
         * @description Состояние связей и «Требуют внимания» на главной (А1, 4.20, 4.30).
         */
        OverviewOut: {
            state: components["schemas"]["ShopState"];
            /** Panel Available */
            panel_available: boolean;
            /** Last Panel Event At */
            last_panel_event_at: string | null;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Attention */
            attention: number;
            /** Waiting Panel */
            waiting_panel: number;
        };
        /**
         * PaletteOut
         * @description Каким станет цвет оператора (1.24).
         */
        PaletteOut: {
            /** Light Primary */
            light_primary: string;
            /** Dark Primary */
            dark_primary: string;
            /** Adjusted */
            adjusted: boolean;
            /** Warnings */
            warnings: components["schemas"]["Semantic"][];
            tokens: components["schemas"]["TokensOut"];
        };
        /** PanelDetailsOut */
        PanelDetailsOut: {
            /** Version */
            version: string | null;
            /** Supported Versions */
            supported_versions: string[];
            /** Error */
            error: ("unavailable" | "unauthorized" | "error" | "incompatible_version") | null;
        };
        /**
         * PanelSettingsOut
         * @description «Панель»: адрес и секрет вебхука для панели (1.9).
         */
        PanelSettingsOut: {
            /** Webhook Url */
            webhook_url: string;
            /** Webhook Secret */
            webhook_secret: string | null;
            /** Webhook Secret Fits Panel */
            webhook_secret_fits_panel: boolean;
        };
        /**
         * Period
         * @enum {string}
         */
        Period: "today" | "7d" | "30d";
        /**
         * RevenueOut
         * @description Выручка и число оплат — только владельцу (1.20).
         */
        RevenueOut: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Payments */
            payments: number;
        };
        /**
         * Semantic
         * @enum {string}
         */
        Semantic: "success" | "warning" | "danger";
        /** ShopSettingsIn */
        ShopSettingsIn: {
            support_contact: components["schemas"]["_Contact"];
            /** Time Zone */
            time_zone: string;
            /** Testers */
            testers: number[];
        };
        /** ShopSettingsOut */
        ShopSettingsOut: {
            /** Support Contact */
            support_contact: string;
            /** Time Zone */
            time_zone: string;
            /** Testers */
            testers: number[];
        };
        /**
         * ShopState
         * @enum {string}
         */
        ShopState: "not_opened" | "open" | "paused";
        /** SquadOut */
        SquadOut: {
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /** Name */
            name: string;
        };
        /** StatsOut */
        StatsOut: {
            period: components["schemas"]["Period"];
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Time Zone */
            time_zone: string;
            /** Active Paid */
            active_paid: number;
            /** Active Trials */
            active_trials: number;
            /** New Clients */
            new_clients: number;
            /** Expiring Soon */
            expiring_soon: number;
            revenue: components["schemas"]["RevenueOut"] | null;
        };
        /**
         * TariffIn
         * @description Тариф «срок + безлимит» (2.1); другие типы — в v1 (2.3).
         */
        TariffIn: {
            /**
             * Type
             * @default term_unlimited
             * @constant
             */
            type: "term_unlimited";
            name: components["schemas"]["remnabay__web__admin___tariffs___Name"];
            /** @default  */
            description: components["schemas"]["_Description"];
            /** Duration Days */
            duration_days: number;
            /** Price */
            price: number | string;
            /** Device Limit */
            device_limit: number;
            /** Squad Uuids */
            squad_uuids: string[];
        };
        /** TariffOut */
        TariffOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            type: components["schemas"]["TariffType"];
            state: components["schemas"]["TariffState"];
            /** Duration Days */
            duration_days: number | null;
            /** Price */
            price: string;
            /** Device Limit */
            device_limit: number;
            /** Squad Uuids */
            squad_uuids: string[];
            /** In Use */
            in_use: boolean;
        };
        /**
         * TariffState
         * @enum {string}
         */
        TariffState: "on_sale" | "archived" | "closed";
        /**
         * TariffType
         * @description Один из четырёх типов; свободная комбинация параметров не допускается (0009).
         * @enum {string}
         */
        TariffType: "term_unlimited" | "term_quota" | "term_package" | "package_only";
        /** TariffsOut */
        TariffsOut: {
            /** Currency */
            currency: string;
            /** Tariffs */
            tariffs: components["schemas"]["TariffOut"][];
        };
        /**
         * TeamRole
         * @description Две фиксированные роли (0004).
         * @enum {string}
         */
        TeamRole: "owner" | "assistant";
        /**
         * TokensOut
         * @description Токены оформления обеих тем: имя → значение CSS.
         */
        TokensOut: {
            /** Light */
            light: {
                [key: string]: string;
            };
            /** Dark */
            dark: {
                [key: string]: string;
            };
        };
        /**
         * Usage
         * @description Почему тариф нельзя удалить, только архивировать (2.8).
         * @enum {string}
         */
        Usage: "subscriptions" | "payments" | "promo_codes" | "successor";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookDetailsOut */
        WebhookDetailsOut: {
            /** Url */
            url: string;
            /** Secret */
            secret: string | null;
        };
        /** WebhookSecretIn */
        WebhookSecretIn: {
            /** Webhook Secret */
            webhook_secret: string;
        };
        _Contact: string;
        _Description: string;
        _Welcome: string;
        remnabay__web__admin___brand___Name: string;
        remnabay__web__admin___tariffs___Name: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_login_request_api_admin_auth_login_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginRequestOut"];
                };
            };
        };
    };
    poll_login_request_api_admin_auth_login_requests_poll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginPollOut"];
                };
            };
        };
    };
    logout_api_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_admin_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
        };
    };
    brand_api_admin_brand_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
        };
    };
    brand_settings_api_admin_settings_brand_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSettingsOut"];
                };
            };
        };
    };
    update_brand_settings_api_admin_settings_brand_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_palette_api_admin_settings_brand_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColorsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaletteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_admin_settings_brand_assets__kind__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["AssetKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_asset_api_admin_settings_brand_assets__kind__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["AssetKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checklist_api_admin_checklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistOut"];
                };
            };
        };
    };
    open_shop_endpoint_api_admin_shop_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyOut"];
                };
            };
        };
    };
    close_shop_endpoint_api_admin_shop_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistOut"];
                };
            };
        };
    };
    overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    shop_settings_api_admin_settings_shop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettingsOut"];
                };
            };
        };
    };
    update_shop_settings_api_admin_settings_shop_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_settings_api_admin_settings_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSettingsOut"];
                };
            };
        };
    };
    update_login_settings_api_admin_settings_login_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    panel_settings_api_admin_settings_panel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSettingsOut"];
                };
            };
        };
    };
    update_webhook_secret_api_admin_settings_panel_webhook_secret_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSecretIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_webhook_secret_api_admin_settings_panel_webhook_secret_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSettingsOut"];
                };
            };
        };
    };
    stats_api_admin_stats_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["Period"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expiring_api_admin_subscriptions_expiring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpiringOut"][];
                };
            };
        };
    };
    tariffs_api_admin_tariffs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffsOut"];
                };
            };
        };
    };
    create_api_admin_tariffs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TariffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    squads_api_admin_panel_squads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadOut"][];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    order_api_admin_tariffs_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_admin_tariffs__tariff_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tariff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TariffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_admin_tariffs__tariff_id__delete: {
        parameters: {
            query?: {
                confirm_last?: boolean;
            };
            header?: never;
            path: {
                tariff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastOnSaleOut"] | components["schemas"]["InUseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_api_admin_tariffs__tariff_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tariff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastOnSaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_admin_tariffs__tariff_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tariff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    about_api_admin_about_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutOut"];
                };
            };
        };
    };
}
