"""Логотипы оператора (1.11, решение 0051)

Revision ID: ceb549393a05
Revises: 509067c5b909
Create Date: 2026-10-06 01:38:28.644030

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceb549393a05"
down_revision: str | Sequence[str] | None = "509067c5b909"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # CHECK для колонок-перечислений создаёт сам sa.Enum(create_constraint=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_assets",
        sa.Column(
            "kind",
            sa.Enum(
                "mark",
                "logo",
                name="brand_asset_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["team_members.id"],
            name=op.f("fk_brand_assets_updated_by_id_team_members"),
        ),
        sa.PrimaryKeyConstraint("kind", name=op.f("pk_brand_assets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("brand_assets")
    # ### end Alembic commands ###
