"""Запросы входа в админку (1.4–1.6, решение 0051)

Revision ID: 509067c5b909
Revises: 5f258a35bcdf
Create Date: 2026-10-06 01:21:03.785073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "509067c5b909"
down_revision: str | Sequence[str] | None = "5f258a35bcdf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # CHECK для колонок-перечислений создаёт сам sa.Enum(create_constraint=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_requests",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "bot_confirm",
                "login_url",
                name="login_method",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "rejected",
                "used",
                name="login_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("poll_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("code", sa.String(length=8), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("team_member_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_member_id"],
            ["team_members.id"],
            name=op.f("fk_login_requests_team_member_id_team_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_requests")),
        sa.UniqueConstraint("poll_hash", name=op.f("uq_login_requests_poll_hash")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_login_requests_token_hash")),
    )
    op.create_index(
        op.f("ix_login_requests_expires_at"), "login_requests", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_requests_expires_at"), table_name="login_requests")
    op.drop_table("login_requests")
    # ### end Alembic commands ###
