"""Настройки магазина (04-operator-settings)

Revision ID: 6291572b61a1
Revises: 4e683cce0a3d
Create Date: 2026-10-05 22:02:40.406134

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6291572b61a1"
down_revision: str | Sequence[str] | None = "4e683cce0a3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["team_members.id"],
            name=op.f("fk_shop_settings_updated_by_id_team_members"),
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_shop_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_settings")
    # ### end Alembic commands ###
